/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Classes.Consumo;
import Classes.Data_transfer;
import Classes.Produto;
import Classes.Usuario;
import DAO.ConsumoDAO;
import DAO.DAO;
import DAO.UsuarioDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PedroMazarini
 */
public class Tela_usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Tela_usuarios
     */
    List<Usuario> lista_usuarios;
    Data_transfer data_transfer;
    public Tela_usuarios(Data_transfer transfer_data) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        data_transfer = new Data_transfer();
        data_transfer = transfer_data;
        bloqueia_tela();
        buttonGroup1.add(radio_atendente);
        buttonGroup1.add(radio_gerente);
    }

    private Tela_usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        radio_gerente = new javax.swing.JRadioButton();
        radio_atendente = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_usuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        text_codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Usuários");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Usuários");

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar.png"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirm2.png"))); // NOI18N
        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Função", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 12))); // NOI18N

        radio_gerente.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        radio_gerente.setSelected(true);
        radio_gerente.setText("Gerente");
        radio_gerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio_gerenteMouseClicked(evt);
            }
        });
        radio_gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gerenteActionPerformed(evt);
            }
        });

        radio_atendente.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        radio_atendente.setText("Atendente");
        radio_atendente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio_atendenteMouseClicked(evt);
            }
        });
        radio_atendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_atendenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radio_atendente)
                    .addComponent(radio_gerente))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radio_gerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_atendente)
                .addContainerGap())
        );

        table_usuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        table_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Código", "Função"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_usuarios.setRowHeight(25);
        table_usuarios.getTableHeader().setResizingAllowed(false);
        table_usuarios.getTableHeader().setReorderingAllowed(false);
        table_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_usuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_usuarios);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("*Clique duplo para apagar usuário.");

        text_codigo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        text_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_codigoKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Código:");

        text_nome.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel3.setText("Nome:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_codigo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton2)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refreshTable (){
        
        int row_counter =0;
            
            DefaultTableModel model = new DefaultTableModel();
            model = (DefaultTableModel) table_usuarios.getModel();
            model.setRowCount(lista_usuarios.size()); 
            for (Usuario u : lista_usuarios){ 
              table_usuarios.setValueAt(u.getNome(), row_counter, 0);   
              table_usuarios.setValueAt(u.getCodigo(), row_counter, 1);  
              if(u.getGerente()==1){
                table_usuarios.setValueAt("Gerente", row_counter, 2);  
              }else{
                table_usuarios.setValueAt("Atendente", row_counter, 2);   
              }
              
              row_counter++; 
            }
        
    }
    
    public void addUsuario (){
        
        try{
            int codigo = Integer.valueOf(text_codigo.getText());        
        
        if(verificaUsuarios(text_codigo.getText())){
        
            DAO dao;  
            Usuario usuario = new Usuario();
            usuario.setCodigo(text_codigo.getText());
            usuario.setNome(text_nome.getText());
            if(radio_gerente.isSelected()){
                usuario.setGerente(1);
            }else{
                usuario.setGerente(0);
            }
            try {
                dao = new UsuarioDAO();
                dao.salvar(usuario);
                lista_usuarios.add(usuario);
                refreshTable();
                text_codigo.setText("");
                text_nome.setText("");
                text_nome.requestFocus();
                data_transfer.getLista_usuarios().add(usuario);

            } catch (SQLException ex) {
                Logger.getLogger(Tela_login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Código ja utilizado por outro usuário!","ERRO",
                         JOptionPane.ERROR_MESSAGE);
            text_codigo.setText("");
            text_codigo.requestFocus();
        }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(rootPane, "Código inválido, digite apenas números!","ERRO",
                         JOptionPane.ERROR_MESSAGE);
            text_codigo.setText("");
            text_codigo.requestFocus();
        }
    }
    
    public boolean verificaUsuarios(String codigo){
        for(Usuario user : lista_usuarios){
            if(codigo.equals(user.getCodigo()))return false;
        }
        return true;
    }
    
    public void bloqueia_tela(){
         boolean autorizado = false;     
            
            lista_usuarios = new ArrayList<Usuario>();
            DAO dao;
            while (autorizado==false){
                String cod_atendente= JOptionPane.showInputDialog(rootPane, "Gerente:", "Login", JOptionPane.QUESTION_MESSAGE);
                try {
                    dao = new UsuarioDAO();
                    lista_usuarios = dao.listarTodos();

                    for (Usuario u : lista_usuarios)
                    {
                       if ((u.getCodigo().equals(cod_atendente))&&(u.getGerente()==1)){
                           autorizado = true;
                           break;
                       }

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Tela_login.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (autorizado== true){  
                    text_nome.requestFocus();
                    refreshTable();

                }else{
                    JOptionPane.showMessageDialog(rootPane, "Acesso Não Autorizado!","ERRO",
                     JOptionPane.ERROR_MESSAGE);
            }
            }
        
    }
    private void radio_gerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_gerenteMouseClicked
        
    }//GEN-LAST:event_radio_gerenteMouseClicked

    private void radio_gerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_gerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_gerenteActionPerformed

    private void radio_atendenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_atendenteMouseClicked
      
    }//GEN-LAST:event_radio_atendenteMouseClicked

    private void radio_atendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_atendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_atendenteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if((!text_codigo.getText().isEmpty())&&(!text_nome.getText().isEmpty())){
          addUsuario();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente!","ERRO",
                         JOptionPane.ERROR_MESSAGE);
            text_nome.requestFocus();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void text_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_codigoKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           if((!text_codigo.getText().isEmpty())&&(!text_nome.getText().isEmpty())){
          addUsuario();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos corretamente!","ERRO",
                         JOptionPane.ERROR_MESSAGE);
            text_nome.requestFocus();
        }
           }
    }//GEN-LAST:event_text_codigoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        data_transfer.getTela_login().setEnabled(true);
        data_transfer.getTela_login().setVisible(true);
        this.setAlwaysOnTop(false);
    }//GEN-LAST:event_formWindowClosed

    private void table_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_usuariosMouseClicked
       
        Usuario usuario = null;
        if (evt.getClickCount() == 2) {
            int row= table_usuarios.getSelectedRow();
            for(Usuario user : lista_usuarios){
                if (user.getCodigo().equals(table_usuarios.getValueAt(row, 1))){
                    Object[] options = {"Sim","Não"};
                                   int resposta = JOptionPane.showOptionDialog(rootPane, "Deseja excluir o seguinte usuário? \nNome: "+user.getNome()
                                           + "\nCódigo: "+user.getCodigo()
                                           + "\nFunção: "+table_usuarios.getValueAt(row, 2), "Apagar item", 0, 3, null, options, options[0]);
                    if(resposta==0){  
                       
                        try {
                            UsuarioDAO usuarioDAO = new UsuarioDAO();
                            usuarioDAO.remover_usuario(user.getCodigo()); 
                            usuario = user;
                            data_transfer.getLista_usuarios().remove(usuario);
                            
                        } catch (SQLException ex) {
                            Logger.getLogger(Tela_usuarios.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } 
                }
            }
            if(usuario!=null)refreshLista(usuario);
        }
    }//GEN-LAST:event_table_usuariosMouseClicked

    public void refreshLista(Usuario user){
        lista_usuarios.remove(user);
        refreshTable();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radio_atendente;
    private javax.swing.JRadioButton radio_gerente;
    private javax.swing.JTable table_usuarios;
    private javax.swing.JTextField text_codigo;
    private javax.swing.JTextField text_nome;
    // End of variables declaration//GEN-END:variables
}
