/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Classes.Comanda;
import Classes.Consumo;
import Classes.Data_transfer;
import Classes.Produto;
import Classes.Usuario;
import DAO.ComandaDAO;
import DAO.ConsumoDAO;
import DAO.DAO;
import DAO.ProdutoDAO;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PedroMazarini
 */
public class Tela_comanda extends javax.swing.JFrame {

    /**
     * Creates new form Tela_comanda
     */
    Data_transfer transfer_data;
    List<Produto> lista_produtos;
    List<Consumo> lista_consumo;
    
    public Tela_comanda(Data_transfer data_transfer) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        transfer_data = data_transfer;
        
    }

    private Tela_comanda() {
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_chegada = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_codigo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        combobox_qtd = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        textfield_produto = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_consumo = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        label_total = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comanda");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMANDA");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nome:");

        label_nome.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        label_nome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        label_chegada.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        label_chegada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_chegada.setText(" ");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Chegada:");

        label_codigo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        label_codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_codigo.setText(" ");

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar.png"))); // NOI18N
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkou2t.png"))); // NOI18N
        jButton2.setText("FECHAR COMANDA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        combobox_qtd.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        combobox_qtd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        combobox_qtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combobox_qtdMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                combobox_qtdMouseReleased(evt);
            }
        });
        combobox_qtd.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combobox_qtdPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combobox_qtd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox_qtdItemStateChanged(evt);
            }
        });
        combobox_qtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_qtdActionPerformed(evt);
            }
        });
        combobox_qtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combobox_qtdFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel2.setText("TOTAL:");

        textfield_produto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textfield_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfield_produtoMouseClicked(evt);
            }
        });
        textfield_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textfield_produtoKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel5.setText("ADD PRODUTO:");

        table_consumo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        table_consumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Qtd", "Hr. Pedido", "Preço Unit.", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_consumo.setRowHeight(25);
        table_consumo.getTableHeader().setResizingAllowed(false);
        table_consumo.getTableHeader().setReorderingAllowed(false);
        table_consumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_consumoMouseClicked(evt);
            }
        });
        table_consumo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                table_consumoFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(table_consumo);
        if (table_consumo.getColumnModel().getColumnCount() > 0) {
            table_consumo.getColumnModel().getColumn(0).setMinWidth(350);
            table_consumo.getColumnModel().getColumn(0).setPreferredWidth(350);
            table_consumo.getColumnModel().getColumn(0).setMaxWidth(350);
            table_consumo.getColumnModel().getColumn(1).setMinWidth(100);
            table_consumo.getColumnModel().getColumn(1).setPreferredWidth(100);
            table_consumo.getColumnModel().getColumn(1).setMaxWidth(100);
            table_consumo.getColumnModel().getColumn(2).setMinWidth(80);
            table_consumo.getColumnModel().getColumn(2).setPreferredWidth(80);
            table_consumo.getColumnModel().getColumn(2).setMaxWidth(80);
            table_consumo.getColumnModel().getColumn(3).setMinWidth(130);
            table_consumo.getColumnModel().getColumn(3).setPreferredWidth(130);
            table_consumo.getColumnModel().getColumn(3).setMaxWidth(130);
            table_consumo.getColumnModel().getColumn(4).setMinWidth(100);
            table_consumo.getColumnModel().getColumn(4).setPreferredWidth(100);
            table_consumo.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("COMSUMO:");

        label_total.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        label_total.setText("R$ 00,00");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel8.setText("QTD:");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("*Clique duplo no item para apaga-lo.");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lista_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_total))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combobox_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(label_total))
                            .addComponent(textfield_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combobox_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_chegada, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(121, 121, 121)
                .addComponent(jButton2)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label_codigo)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(label_chegada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobox_qtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_qtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_qtdActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        transfer_data.getFrame().setEnabled(true);
        transfer_data.getFrame().setVisible(true);
        transfer_data.getFrame().requestFocus();     
        
        
    }//GEN-LAST:event_formWindowClosed

   
    public void refreshTable (){
        
        lista_produtos = new ArrayList<Produto>();
        lista_produtos = transfer_data.getLista_produtos();
        DAO dao;
        float total=0;
        int row_counter =0;
        lista_consumo = new ArrayList<Consumo>();
        try {
            dao = new ConsumoDAO();
            lista_consumo = dao.listarConsumo(transfer_data.getComanda().getId());
            DefaultTableModel model = new DefaultTableModel();
            model = (DefaultTableModel) table_consumo.getModel();
            model.setRowCount(lista_consumo.size()); 
            for (Consumo c : lista_consumo){ 
              
               for (Produto p : lista_produtos){ 
                   if(p.getId_produto()==c.getIdproduto()){
                      if(p.getPorkilo()==1){
                          table_consumo.setValueAt(String.format("%.3f",c.getQuantidade())+"Kg", row_counter, 1);
                          table_consumo.setValueAt("R$ "+String.format("%.2f",p.getPreco())+"/Kg", row_counter, 3);
                      } else{
                          table_consumo.setValueAt(String.format("%.0f",c.getQuantidade()), row_counter, 1);
                          table_consumo.setValueAt("R$ "+String.format("%.2f",p.getPreco()), row_counter, 3);
                      }
                      table_consumo.setValueAt(p.getNome(), row_counter, 0);                       
                      String hora = new SimpleDateFormat("HH:mm").format(c.getHr_consumo());
                      table_consumo.setValueAt(hora, row_counter, 2);                      
                      table_consumo.setValueAt("R$ "+String.format("%.2f",(p.getPreco()*c.getQuantidade())), row_counter, 4);
                      total = total +(Float.valueOf(c.getQuantidade())*p.getPreco());                     
                      label_total.setText("R$ "+ String.format("%.2f",total));
                      row_counter++;
                   }
               }
                    
               
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(Tela_login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private float porKilo(){
        boolean pesoOkay=false;
        float peso;
        while(!pesoOkay){
            try{ 
                String response =JOptionPane.showInputDialog(rootPane, "Digite o peso em Kg:", "Peso", JOptionPane.QUESTION_MESSAGE); 
                if ((response != null) && (response.length() > 0)) {
                        peso = Float.valueOf(String.format("%.3f",Float.valueOf(response)));
                        pesoOkay=true;
                        return peso;
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Valor incorreto, digite novamente!!","ERRO",
                         JOptionPane.ERROR_MESSAGE);
                        pesoOkay=false;
                }
                
            }catch(NumberFormatException ex){
               JOptionPane.showMessageDialog(rootPane, "Valor incorreto, digite novamente!","ERRO",
                         JOptionPane.ERROR_MESSAGE);
               pesoOkay=false;
           }
        }        
        return 0;
    }
    
    private boolean verificaKilo(Consumo c){
        for(Produto p : lista_produtos){
            if(c.getIdproduto() == p.getId_produto()){
                if(p.getPorkilo()==0){
                    return false;
                }else{
                    return true;
                }
            }
        }
        return false;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        label_codigo.setText(String.valueOf(transfer_data.getComanda().getBar_code()));
        label_nome.setText(transfer_data.getComanda().getNome());
        label_chegada.setText(String.valueOf(transfer_data.getChegada()));
        textfield_produto.requestFocus();
        refreshTable();
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    public void add_Produto(String codigo){
        DAO dao;
        DAO daoComanda;
        float peso = 0.3f;
        boolean valido = false;
        try {
            dao = new ConsumoDAO();
            Consumo consumo = new Consumo();
            daoComanda = new ComandaDAO();
            
            for (Produto p : transfer_data.getLista_produtos())
            {               
               if (p.getBar_code().equals(codigo)){
                   if(p.getPorkilo()==1){
                      peso = porKilo();
                      consumo.setQuantidade(peso);
                   }else{
                       consumo.setQuantidade(Float.valueOf((String)combobox_qtd.getSelectedItem()));
                   }
                   consumo.setIdcomanda( transfer_data.getComanda().getId());
                   consumo.setIdproduto(p.getId_produto());                   
                   dao.salvar(consumo);
                   refreshTable();
                   valido = true;
                   textfield_produto.setText("");
                   combobox_qtd.setSelectedItem("1");
                   transfer_data.getComanda().setTotal(transfer_data.getComanda().getTotal()+(consumo.getQuantidade()*p.getPreco()));
                   
                   daoComanda.alterar_total(transfer_data.getComanda().getTotal(), transfer_data.getComanda().getId());
                   break;
               }               
            }
             
        } catch (SQLException ex) {
            Logger.getLogger(Tela_login.class.getName()).log(Level.SEVERE, null, ex);
        }catch (NumberFormatException ex) {
            valido= false;
        }
        
        for(Usuario user: transfer_data.getLista_usuarios()){
            if (user.getCodigo().equals(textfield_produto.getText())){
                valido=true;
                this.dispose();
                transfer_data.getTela_login().bloqueia_tela();
            }
        }
        if(!valido){
            JOptionPane.showMessageDialog(rootPane, "Código inválido!","ERRO",
                     JOptionPane.ERROR_MESSAGE);
            textfield_produto.setText("");
        }
        
    }
    private void textfield_produtoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfield_produtoKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           if(!textfield_produto.getText().isEmpty()){               
                add_Produto(textfield_produto.getText());
           }
       }
    }//GEN-LAST:event_textfield_produtoKeyPressed

    private void combobox_qtdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox_qtdItemStateChanged
       textfield_produto.requestFocus();
    }//GEN-LAST:event_combobox_qtdItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textfield_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfield_produtoMouseClicked
        Tela_comanda tela = new Tela_comanda();
        tela = this;
        Tela_produtos t_produtos = new Tela_produtos(lista_produtos, tela);
        t_produtos.setVisible(true);
        tela.setEnabled(false);
      
    }//GEN-LAST:event_textfield_produtoMouseClicked

    private void combobox_qtdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobox_qtdMouseClicked
        textfield_produto.requestFocus();
    }//GEN-LAST:event_combobox_qtdMouseClicked

    private void combobox_qtdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combobox_qtdFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_qtdFocusGained

    private void combobox_qtdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobox_qtdMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_qtdMouseReleased

    private void combobox_qtdPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combobox_qtdPopupMenuWillBecomeInvisible
       textfield_produto.requestFocus();
    }//GEN-LAST:event_combobox_qtdPopupMenuWillBecomeInvisible

    private void table_consumoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_table_consumoFocusGained
        textfield_produto.requestFocus();
    }//GEN-LAST:event_table_consumoFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Tela_fecha_comanda tela_fecha = new Tela_fecha_comanda();
        this.hide();
        tela_fecha.setVisible(true);        
        tela_fecha.initiate_variables(this, lista_consumo, transfer_data);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_consumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_consumoMouseClicked
        Point p = evt.getPoint();
        int table_row = table_consumo.getSelectedRow();
        boolean para = false;
       
        if (evt.getClickCount() == 2) {
            for(Consumo c :lista_consumo){
                String hora = new SimpleDateFormat("HH:mm").format(c.getHr_consumo());
                for(Produto produtos : lista_produtos){
                   if((table_consumo.getValueAt(table_row, 0)==produtos.getNome())&&(produtos.getId_produto()==c.getIdproduto())
                           &&(hora.equals(table_consumo.getValueAt(table_row, 2)))) {
                       String qtd = (String) table_consumo.getValueAt(table_row, 1);
                       Object quantidade;
                       if(verificaKilo(c)){
                           qtd = qtd.substring(0,qtd.length()-2);
                       }
                       if(c.getQuantidade()== Float.valueOf(qtd)){
                           Object[] options = {"Sim","Não"};
                           int resposta = JOptionPane.showOptionDialog(rootPane, "Deseja excluir o seguinte item? \n"+produtos.getNome()
                                   + "\nPreço:"+String.format("%.2f",produtos.getPreco())
                                   + "\nQuantidade: "+c.getQuantidade(), "Apagar item", 0, 3, null, options, options[0]);
                           if(resposta==0){        
                                try{
                                   ComandaDAO comandaDAO = new ComandaDAO();
                                   transfer_data.getComanda().setTotal(transfer_data.getComanda().getTotal()- (produtos.getPreco()*c.getQuantidade()));
                                   comandaDAO.alterar_total(transfer_data.getComanda().getTotal(), transfer_data.getComanda().getId());
                                   ConsumoDAO consumoDAO = new ConsumoDAO(); 
                                   consumoDAO.remover_consumo(c.getIdconsumo());
                                   refreshTable();
                                   float soma = (transfer_data.getComanda().getTotal());                     
                                   label_total.setText("R$ "+ String.format("%.2f",soma));
                                   para=true;
                                } catch (SQLException ex) {
                                 Logger.getLogger(Tela_login.class.getName()).log(Level.SEVERE, null, ex);
                                   }
                           }
                       }
                       
                   }
                   if(para)break;
                }
                if(para)break;
            }
        }
    }//GEN-LAST:event_table_consumoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Tela_comanda tela = new Tela_comanda();
        tela = this;
        Tela_produtos t_produtos = new Tela_produtos(lista_produtos, tela);
        t_produtos.setVisible(true);
        tela.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    public void set_combo_qtd (String item){
        combobox_qtd.setSelectedItem(item);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_comanda().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox_qtd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_chegada;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_total;
    private javax.swing.JTable table_consumo;
    private javax.swing.JFormattedTextField textfield_produto;
    // End of variables declaration//GEN-END:variables
}
